-- size of the actual window 
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

-- size we are trying to emulate with push
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

-- world
MAP_WIDTH = 1000
MAP_HEIGHT = 10
SKY_MAX_INDEX = 8
PILAR_HEIGHT = 2

-- should be a value that JUMP_VELOCITY % GRAVITY_FORCE !== 0 
GRAVITY_FORCE = 9

-- tile's ID
GROUND_INDEX = 1
GROUND_TOPPER_INDEX = 2
BRICK_INDEX = 3
BLANK_INDEX = 4

COLLIDABLE_TILE_INDEX = {GROUND_INDEX, GROUND_TOPPER_INDEX, BRICK_INDEX}

-- tile's size
TILE_WIDTH = 16
TILE_HEIGHT = 16

-- camera
cameraScroll = 0;

-- character
CHARACTER_WIDTH = 18
CHARACTER_HEIGHT = 18
CHARACTER_SPEED = 50
JUMP_VELOCITY = -250
